sonar.projectKey=donantes-api
sonar.projectName=API Registro de Donantes
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=node_modules/**,coverage/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/server.js
